for i in range(N):
 for j in range(N):
  if(i==0 and j==0):
    print("def FFT_$"+ str(i)+str(j))
    print('( .clk(clk), .rst(reset),')
    print(".local_in"+"(local_in"+str(i)+str(j)+")"+",")
    print(".east_in"+"(east_in"+str(i)+str(j)+")"+",")
    print(".west_in"+"("+")"+",")
    print(".north_in"+"("+")"+",")
    print(".south_in"+"(south_in"+str(i)+str(j)+")"+",")
    print(".local_out"+"(local_out"+str(i)+str(j)+")"+",")
    print(".east_out"+"(east_out"+str(i)+str(j)+")"+",")
    print(".west_out"+"("+")"+",")
    print(".north_out"+"("+")"+",")
    print(".south_out"+"(south_out"+str(i)+str(j)+")"+",")
    print(');')
  if(i==0 and j==N-1):
    print("def FFT_$"+ str(i)+str(j))
    print('( .clk(clk), .rst(reset),')
    print(".local_in"+"(local_in"+str(i)+str(j)+")"+",")
    print(".east_in"+"("+")"+",")
    print(".west_in"+"(west_in"+str(i)+str(j)+")"+",")
    print(".north_in"+"("+")"+",")
    print(".south_in"+"(south_in"+str(i)+str(j)+")"+",")
    print(".local_out"+"(local_out"+str(i)+str(j)+")"+",")
    print(".east_out"+"("+")"+",")
    print(".west_out"+"(west_out"+str(i)+str(j)+")"+",")
    print(".north_out"+"("+")"+",")
    print(".south_out"+"(south_out"+str(i)+str(j)+")"+",")
    print(');')
  if(i==N-1 and j==0):
    print("def FFT_$"+ str(i)+str(j))
    print('( .clk(clk), .rst(reset),')
    print(".local_in"+"(local_in"+str(i)+str(j)+")"+",")
    print(".east_in"+"(east_in"+str(i)+str(j)+")"+",")
    print(".west_in"+"("+")"+",")
    print(".north_in"+"(north_in"+str(i)+str(j)+")"+",")
    print(".south_in"+"("+")"+",")
    print(".local_out"+"(local_out"+str(i)+str(j)+")"+",")
    print(".east_out"+"(east_out"+str(i)+str(j)+")"+",")
    print(".west_out"+"("+")"+",")
    print(".north_out"+"(north_out"+str(i)+str(j)+")"+",")
    print(".south_out"+"("+")"+",")
    print(');')
  if(i==N-1 and j==N-1):
    print("def FFT_$"+ str(i)+str(j))
    print('( .clk(clk), .rst(reset),')
    print(".local_in"+"(local_in"+str(i)+str(j)+")"+",")
    print(".east_in"+"("+")"+",")
    print(".west_in"+"(west_in"+str(i)+str(j)+")"+",")
    print(".north_in"+"(north_in"+str(i)+str(j)+")"+",")
    print(".south_in"+"("+")"+",")
    print(".local_out"+"(local_out"+str(i)+str(j)+")"+",")
    print(".east_out"+"("+")"+",")
    print(".west_out"+"(west_out"+str(i)+str(j)+")"+",")
    print(".north_out"+"(north_out"+str(i)+str(j)+")"+",")
    print(".south_out"+"("+")"+",")
    print(');')
  if(j==0 and i!=0 and i!=N-1):
    print("def FFT_$"+ str(i)+str(j))
    print('( .clk(clk), .rst(reset),')
    print(".local_in"+"(local_in"+str(i)+str(j)+")"+",")
    print(".east_in"+"(east_in"+str(i)+str(j)+")"+",")
    print(".west_in"+"("+")"+",")
    print(".north_in"+"(north_in"+str(i)+str(j)+")"+",")
    print(".south_in"+"(south_in"+str(i)+str(j)+")"+",")
    print(".local_out"+"(local_out"+str(i)+str(j)+")"+",")
    print(".east_out"+"(east_out"+str(i)+str(j)+")"+",")
    print(".west_out"+"("+")"+",")
    print(".north_out"+"(north_out"+str(i)+str(j)+")"+",")
    print(".south_out"+"(south_out"+str(i)+str(j)+")"+",")
    print(');')
  if(j==N-1 and i!=0 and i!=N-1):
    print("def FFT_$"+ str(i)+str(j))
    print('( .clk(clk), .rst(reset),')
    print(".local_in"+"(local_in"+str(i)+str(j)+")"+",")
    print(".east_in"+"("+")"+",")
    print(".west_in"+"(west_in"+str(i)+str(j)+")"+",")
    print(".north_in"+"(north_in"+str(i)+str(j)+")"+",")
    print(".south_in"+"(south_in"+str(i)+str(j)+")"+",")
    print(".local_out"+"(local_out"+str(i)+str(j)+")"+",")
    print(".east_out"+"("+")"+",")
    print(".west_out"+"(west_out"+str(i)+str(j)+")"+",")
    print(".north_out"+"(north_out"+str(i)+str(j)+")"+",")
    print(".south_out"+"(south_out"+str(i)+str(j)+")"+",")
    print(');')
  if(i==0 and j!=0 and j!=N-1):
    print("def FFT_$"+ str(i)+str(j))
    print('( .clk(clk), .rst(reset),')
    print(".local_in"+"(local_in"+str(i)+str(j)+")"+",")
    print(".east_in"+"(east_in"+str(i)+str(j)+")"+",")
    print(".west_in"+"(west_in"+str(i)+str(j)+")"+",")
    print(".north_in"+"("+")"+",")
    print(".south_in"+"(south_in"+str(i)+str(j)+")"+",")
    print(".local_out"+"(local_out"+str(i)+str(j)+")"+",")
    print(".east_out"+"(east_out"+str(i)+str(j)+")"+",")
    print(".west_out"+"(west_out"+str(i)+str(j)+")"+",")
    print(".north_out"+"("+")"+",")
    print(".south_out"+"(south_out"+str(i)+str(j)+")"+",")
    print(');')
  if(i==N-1 and j!=0 and j!=N-1):
    print("def FFT_$"+ str(i)+str(j))
    print('( .clk(clk), .rst(reset),')
    print(".local_in"+"(local_in"+str(i)+str(j)+")"+",")
    print(".east_in"+"(east_in"+str(i)+str(j)+")"+",")
    print(".west_in"+"(west_in"+str(i)+str(j)+")"+",")
    print(".north_in"+"(north_in"+str(i)+str(j)+")"+",")
    print(".south_in"+"("+")"+",")
    print(".local_out"+"(local_out"+str(i)+str(j)+")"+",")
    print(".east_out"+"(east_out"+str(i)+str(j)+")"+",")
    print(".west_out"+"(west_out"+str(i)+str(j)+")"+",")
    print(".north_out"+"(north_out"+str(i)+str(j)+")"+",")
    print(".south_out"+"("+")"+",")
    print(');')
  if(i!=0 and i!=N-1 and j!=0 and j!=N-1):
    print("def FFT_$"+ str(i)+str(j))
    print('( .clk(clk), .rst(reset),')
    print(".local_in"+"(local_in"+str(i)+str(j)+")"+",")
    print(".east_in"+"(east_in"+str(i)+str(j)+")"+",")
    print(".west_in"+"(west_in"+str(i)+str(j)+")"+",")
    print(".north_in"+"(north_in"+str(i)+str(j)+")"+",")
    print(".south_in"+"(south_in"+str(i)+str(j)+")"+",")
    print(".local_out"+"(local_out"+str(i)+str(j)+")"+",")
    print(".east_out"+"(east_out"+str(i)+str(j)+")"+",")
    print(".west_out"+"(west_out"+str(i)+str(j)+")"+",")
    print(".north_out"+"(north_out"+str(i)+str(j)+")"+",")
    print(".south_out"+"(south_out"+str(i)+str(j)+")"+",")
    print(');')

